ALTER TABLE public.points_of_interest ADD COLUMN is_paid BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.transportation ADD COLUMN is_paid BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.expenses ADD COLUMN is_paid BOOLEAN NOT NULL DEFAULT FALSE;
