project_id = "aqpzhflzsqkjceeeufyf"

[functions.travel-webhook]
verify_jwt = false

[functions.recommendation-webhook]
verify_jwt = false

[functions.sync-maps-list]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.search-country-resources]
verify_jwt = false

[functions.cognito-auth-bridge]
verify_jwt = false