// ──────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED from config.json — do not edit manually.
// Regenerate: cd frontend && npm run generate:categories
// ──────────────────────────────────────────────────────────────────────────────

/** Maps extracted item type → DB entity category. */
export const TYPE_TO_CATEGORY: Record<string, string> = {
  river: 'attraction', delta: 'attraction', fjord: 'attraction', plateau: 'attraction', 
  desert: 'attraction', glacier: 'attraction', reef: 'attraction', peninsula: 'attraction', 
  harbor: 'attraction', old_town: 'attraction', monastery: 'attraction', church: 'attraction', 
  synagogue: 'attraction', mosque: 'attraction', shrine: 'attraction', pagoda: 'attraction', 
  mountain_range: 'attraction', valley: 'attraction', canyon: 'attraction', volcano: 'attraction', 
  waterfall: 'attraction', lagoon: 'attraction', bay: 'attraction', lake: 'attraction', 
  coastline: 'attraction', national_park_area: 'attraction', nature_reserve_area: 'attraction', 
  transit_hub_area: 'attraction', resort_complex: 'attraction', itinerary_route: 'attraction', 
  border_crossing: 'attraction', point_of_interest: 'attraction', reserve_area: 'attraction', 
  forest_area: 'attraction', cave_area: 'attraction', market: 'attraction', 
  night_market: 'attraction', park: 'attraction', landmark: 'attraction', natural: 'attraction', 
  historical: 'attraction', cultural: 'attraction', amusement: 'attraction', beach: 'attraction', 
  mountain: 'attraction', wildlife: 'attraction', adventure: 'attraction', religious: 'attraction', 
  architectural: 'attraction', underwater: 'attraction', national_park: 'attraction', 
  scenic: 'attraction', museum: 'attraction', shopping: 'attraction', zoo: 'attraction', 
  theme_park: 'attraction', botanical_garden: 'attraction', sports: 'attraction', 
  music: 'attraction', art: 'attraction', nightlife: 'attraction', spa: 'attraction', 
  casino: 'attraction', viewpoint: 'attraction', hiking_trail: 'attraction', 
  extreme_sports: 'attraction', hidden_gem: 'attraction', beach_club: 'attraction', 
  stargazing: 'attraction', street_art: 'attraction', photography_spot: 'attraction', 
  temple: 'attraction', boat_tour: 'attraction', playground: 'attraction', 
  walking_tour: 'attraction', shopping_mall: 'attraction', historic_site: 'attraction', 
  water_park: 'attraction', ski_resort: 'attraction', vineyard: 'eatery', brewery: 'eatery', 
  movie_theater: 'attraction', concert_hall: 'attraction', botanical_park: 'attraction', 
  fishing_spot: 'attraction', bird_sanctuary: 'attraction', zip_line: 'attraction', 
  hot_spring: 'attraction', gym: 'attraction', massage: 'attraction', yoga_studio: 'attraction', 
  meditation_center: 'attraction', thermal_bath: 'attraction', canyon_activity: 'attraction', 
  volcano_activity: 'attraction', observatory: 'attraction', lighthouse: 'attraction', 
  art_gallery: 'attraction', aquarium: 'attraction', cave: 'attraction', snorkeling: 'attraction', 
  diving_activity: 'attraction', surfing: 'attraction', kayaking_activity: 'attraction', 
  rafting: 'attraction', climbing: 'attraction', trekking: 'attraction', jeep_tour: 'attraction', 
  safari: 'attraction', food_tour: 'attraction', street_market_tour: 'attraction', 
  cooking_class: 'attraction', wine_tasting: 'attraction', brewery_tour: 'attraction', 
  kids_attraction: 'attraction', castle: 'attraction', fortress: 'attraction', 
  palace: 'attraction', ruins: 'attraction', archaeological_site: 'attraction', 
  memorial: 'attraction', statue: 'attraction', monument: 'attraction', fountain: 'attraction', 
  garden: 'attraction', arboretum: 'attraction', heritage_site: 'attraction', 
  unesco_site: 'attraction', sunset_spot: 'attraction', sunrise_spot: 'attraction', 
  panoramic_view: 'attraction', romantic_spot: 'attraction', instagram_spot: 'attraction', 
  picnic_area: 'attraction', campfire_site: 'attraction', cape: 'attraction', strait: 'attraction', 
  basin: 'attraction', cliff: 'attraction', ridge: 'attraction', wetland: 'attraction', 
  marsh: 'attraction', savanna: 'attraction', steppe: 'attraction', tundra: 'attraction', 
  oasis: 'attraction', gorge: 'attraction', sand_dune: 'attraction', 
  hot_desert_spring: 'attraction', street_food_lane: 'attraction', craft_market: 'attraction', 
  local_farm_visit: 'attraction', cooking_workshop: 'attraction', photo_tour: 'attraction', 
  wine_route: 'attraction', cycling_route: 'attraction', pilgrimage_route: 'attraction', 
  dining: 'attraction', sightseeing: 'attraction', swimming_activity: 'attraction', 
  strolling: 'attraction', relaxation: 'attraction', shopping_activity: 'attraction', 
  logistics_setup: 'attraction', transit_activity: 'attraction', other_activity: 'attraction', 
  national_holiday: 'event', religious_holiday: 'event', cultural_festival: 'event', 
  festival: 'event', music_festival: 'event', carnival: 'event', cultural_parade: 'event', 
  food_festival: 'event', art_exhibition: 'event', fireworks: 'event', sporting_event: 'event', 
  local_festival: 'event', religious_festival: 'event', street_parade: 'event', 
  sports_match: 'event', marathon: 'event', concert: 'event', theater_show: 'event', 
  food_fair: 'event', film_festival: 'event', fashion_show: 'event', food_truck_fair: 'event', 
  hotel: 'accommodation', glamping: 'accommodation', hostel: 'accommodation', 
  villa: 'accommodation', resort: 'accommodation', apartment_stay: 'accommodation', 
  guesthouse: 'accommodation', bed_and_breakfast: 'accommodation', motel: 'accommodation', 
  lodge: 'accommodation', eco_lodge: 'accommodation', boutique_hotel: 'accommodation', 
  capsule_hotel: 'accommodation', ryokan: 'accommodation', homestay: 'accommodation', 
  farm_stay: 'accommodation', cottage: 'accommodation', chalet: 'accommodation', 
  bungalow: 'accommodation', treehouse: 'accommodation', houseboat: 'accommodation', 
  campground: 'accommodation', camping_tent: 'accommodation', rv_park: 'accommodation', 
  serviced_apartment: 'accommodation', long_stay_hotel: 'accommodation', 
  luxury_hotel: 'accommodation', budget_hotel: 'accommodation', 
  other_accommodation: 'accommodation', mountain_hut: 'accommodation', 
  desert_camp: 'accommodation', surf_hostel: 'accommodation', diving_resort: 'accommodation', 
  ski_lodge: 'accommodation', wellness_resort: 'accommodation', business_hotel: 'accommodation', 
  airport_hotel: 'accommodation', city_aparthotel: 'accommodation', restaurant: 'eatery', 
  cafe: 'eatery', bakery: 'eatery', deli: 'eatery', bistro: 'eatery', diner: 'eatery', 
  food_truck: 'eatery', food_court: 'eatery', buffet: 'eatery', ice_cream_parlor: 'eatery', 
  juice_bar: 'eatery', pub: 'eatery', bar: 'eatery', tavern: 'eatery', wine_bar_eatery: 'eatery', 
  brewpub: 'eatery', sushi_bar: 'eatery', teahouse: 'eatery', steakhouse: 'eatery', 
  tapas_bar: 'eatery', doughnut_shop: 'eatery', dessert_bar: 'eatery', street_food: 'eatery', 
  rooftop_bar: 'eatery', brunch_spot: 'eatery', speakeasy: 'eatery', fine_dining: 'eatery', 
  local_cuisine: 'eatery', vegan_restaurant: 'eatery', vegetarian_restaurant: 'eatery', 
  seafood_restaurant: 'eatery', family_restaurant: 'eatery', other_eatery: 'eatery', 
  ramen_shop: 'eatery', burger_joint: 'eatery', pizza_place: 'eatery', patisserie: 'eatery', 
  gelato_shop: 'eatery', cocktail_bar: 'eatery', food_hall: 'eatery', local_bakery_cafe: 'eatery', 
  gelato_stand: 'eatery', car: 'transportation', bus: 'transportation', train: 'transportation', 
  subway: 'transportation', bicycle: 'transportation', motorcycle: 'transportation', 
  taxi: 'transportation', ferry: 'transportation', airplane: 'transportation', 
  scooter: 'transportation', cruise: 'transportation', tram: 'transportation', 
  cruise_ship: 'transportation', car_rental: 'transportation', domestic_flight: 'transportation', 
  international_flight: 'transportation', night_train: 'transportation', 
  high_speed_train: 'transportation', cable_car: 'transportation', funicular: 'transportation', 
  boat_taxi_transport: 'transportation', rideshare: 'transportation', 
  private_transfer: 'transportation', rv: 'transportation', bus_stop: 'transportation', 
  bus_station: 'transportation', train_station: 'transportation', 
  railway_station: 'transportation', subway_station: 'transportation', 
  metro_station: 'transportation', tram_stop: 'transportation', tram_station: 'transportation', 
  light_rail_station: 'transportation', ferry_terminal: 'transportation', 
  harbor_terminal: 'transportation', port: 'transportation', airport: 'transportation', 
  airport_terminal: 'transportation', heliport: 'transportation', 
  cable_car_station: 'transportation', funicular_station: 'transportation', 
  park_and_ride: 'transportation', taxi_stand: 'transportation', 
  ride_share_pickup: 'transportation', transport_hub: 'transportation', 
  intermodal_terminal: 'transportation', other_transportation: 'transportation', 
  border_terminal: 'transportation', toll_station: 'transportation', 
  highway_rest_area: 'transportation', gas_station: 'transportation', 
  parking_garage: 'transportation', ev_charging_station: 'transportation', 
  bike_station: 'transportation', shuttle_bus: 'transportation', 
  airport_shuttle_bus: 'transportation', harbor_shuttle_boat: 'transportation', atm: 'service', 
  travel_agency: 'service', laundry: 'service', sim_card: 'service', hospital: 'service', 
  pharmacy: 'service', currency_exchange: 'service', luggage_storage: 'service', 
  tourist_info: 'service', supermarket: 'service', tour_guide: 'service', 
  driver_service: 'service', bike_rental: 'service', scooter_rental: 'service', 
  equipment_rental: 'service', locker: 'service', shower_facility: 'service', 
  wifi_hotspot: 'service', coworking_space: 'service', embassy: 'service', 
  other_service: 'service', post_office: 'service', police_station: 'service', 
  fire_station: 'service', clinic: 'service', dentist: 'service', vet: 'service', bank: 'service', 
  money_transfer: 'service', convenience_store: 'service', local_sim_shop: 'service', 
  luggage_repair: 'service', camera_repair: 'service', tour_guide_contact: 'contact', 
  host_contact: 'contact', driver_contact: 'contact', agency_contact: 'contact', 
  rental_contact: 'contact', restaurant_contact: 'contact', other_contact: 'contact', 
  running_track: 'attraction', race_track: 'attraction', horse_riding: 'attraction', 
  golf_course: 'attraction', basketball_court: 'attraction', soccer_field: 'attraction', 
  stadium: 'attraction', tennis_court: 'attraction', swimming_pool: 'attraction', 
  cemetery: 'attraction', library: 'attraction', coffee_shop: 'attraction', 
  nightclub: 'attraction', snooker: 'attraction', bowling: 'attraction', escape_room: 'attraction', 
  illusion_museum: 'attraction', arcade: 'attraction', climbing_wall: 'attraction'
};

/** All non-geo types as a comma-separated string (for AI prompts). */
export const ALLOWED_TYPES_CSV = Object.keys(TYPE_TO_CATEGORY).join(', ');

/** Geographic location types (not actionable POIs). */
export const GEO_TYPES = new Set([
  'continent', 'country', 'square', 'plaza', 'street', 'avenue', 'boulevard', 'alley', 'lane', 
  'promenade', 'waterfront', 'esplanade', 'roundabout', 'intersection', 'bridge', 'tunnel', 
  'overpass', 'underpass', 'stairs', 'path', 'walkway', 'pier', 'quay', 'embankment', 'county', 
  'republic', 'oblast', 'borough', 'quarter', 'federal_entity', 'autonomous_community', 'canton', 
  'voivodeship', 'capital_city', 'entity', 'federal_city', 'state', 'province', 'territory', 
  'region', 'tourism_region', 'metropolitan_area', 'municipality', 'city', 'town', 'village', 
  'suburb', 'district', 'neighborhood', 'pedestrian_zone', 'historic_district', 'department', 
  'township', 'governorate', 'metropolis', 'prefecture', 'area', 'atoll', 'other_geography', 
  'river', 'delta', 'fjord', 'plateau', 'desert', 'glacier', 'reef', 'peninsula', 'harbor', 
  'old_town', 'monastery', 'church', 'synagogue', 'mosque', 'shrine', 'pagoda', 'mountain_range', 
  'valley', 'canyon', 'volcano', 'waterfall', 'lagoon', 'bay', 'lake', 'coastline', 
  'national_park_area', 'nature_reserve_area', 'transit_hub_area', 'resort_complex', 
  'itinerary_route', 'border_crossing', 'point_of_interest', 'reserve_area', 'forest_area', 
  'cave_area', 'market', 'night_market', 'gym', 'massage', 'yoga_studio', 'meditation_center', 
  'thermal_bath', 'cape', 'strait', 'basin', 'cliff', 'ridge', 'wetland', 'marsh', 'savanna', 
  'steppe', 'tundra', 'oasis', 'gorge', 'sand_dune', 'hot_desert_spring', 'bus_stop', 
  'bus_station', 'train_station', 'railway_station', 'subway_station', 'metro_station', 
  'tram_stop', 'tram_station', 'light_rail_station', 'ferry_terminal', 'harbor_terminal', 'port', 
  'airport', 'airport_terminal', 'heliport', 'cable_car_station', 'funicular_station', 
  'park_and_ride', 'taxi_stand', 'ride_share_pickup', 'transport_hub', 'intermodal_terminal', 
  'border_terminal', 'toll_station', 'highway_rest_area', 'gas_station', 'parking_garage', 
  'ev_charging_station', 'bike_station', 'atm', 'travel_agency', 'laundry', 'hospital', 'pharmacy', 
  'currency_exchange', 'luggage_storage', 'tourist_info', 'supermarket', 'bike_rental', 
  'scooter_rental', 'equipment_rental', 'locker', 'shower_facility', 'coworking_space', 'embassy', 
  'post_office', 'police_station', 'fire_station', 'clinic', 'dentist', 'vet', 'bank', 
  'money_transfer', 'convenience_store', 'local_sim_shop', 'luggage_repair', 'camera_repair', 
  'running_track', 'race_track', 'horse_riding', 'golf_course', 'basketball_court', 'soccer_field', 
  'stadium', 'tennis_court', 'swimming_pool', 'cemetery', 'library', 'coffee_shop', 'nightclub', 
  'snooker', 'bowling', 'escape_room', 'illusion_museum', 'arcade', 'climbing_wall'
]);

/** Geo types as a comma-separated string (for AI prompts). */
export const GEO_TYPES_CSV = [...GEO_TYPES].join(', ');

/** Tip types — informational, not entities. */
export const TIP_TYPES = new Set([
  'best_time_visit', 'safety_tip', 'packing_tip', 'app_recommendation', 'budget_tip', 
  'transport_tip', 'scam_warning', 'weather_tip', 'health_tip', 'visa_tips', 'money_tip', 
  'local_etiquette_tip', 'connectivity_tip', 'family_travel_tip', 'emergency_number_tip', 
  'other_tip'
]);

export function getCategoryForType(type: string): string | undefined {
  return TYPE_TO_CATEGORY[type];
}

export function isGeographicType(type: string): boolean {
  return GEO_TYPES.has(type);
}
